/**
 * Candidate profile used by the weighted scoring engine.
 * Compares job responsibilities against this background — not simple keyword matching.
 */
export const CANDIDATE_PROFILE = {
  name: "Senior Design Systems Leader",
  targetSeniority: ["ic6", "staff", "principal", "lead"] as const,
  defaultRoleFocus: "design_systems" as const,
  excludeManagerOnly: true,

  background: {
    title: "Senior / Product Design Lead",
    highlights: [
      "Deep design systems experience at Meta/Facebook on one of the world's largest design systems",
      "Scalable UI systems, component strategy, governance, accessibility, documentation, adoption",
      "Cross-functional partnerships and design/engineering alignment",
      "Design system adoption across many teams",
      "Facebook Design System / Blueprint-style component libraries",
      "Design system quality, component contribution models, documentation standards",
      "Accessibility improvements, token strategy, AI-ready documentation/specs",
    ],
    caseStudyThemes: [
      "design system quality and governance",
      "entity header / shared system abstractions",
      "notifications migration",
      "ads link attachment footer",
      "marketplace profile dating groups events partnerships",
      "accessibility WCAG AA AAA improvements",
      "system adoption experimentation velocity engineering efficiency",
    ],
  },

  /** Experience dimensions scored in responsibility overlap (25% weight) */
  experienceDimensions: [
    {
      id: "design_system_strategy",
      label: "Design system strategy",
      signals: [
        "design system strategy",
        "system roadmap",
        "design system vision",
        "platform design strategy",
        "design infrastructure",
      ],
      weight: 1.2,
    },
    {
      id: "component_architecture",
      label: "Component architecture",
      signals: [
        "component library",
        "component architecture",
        "ui components",
        "design tokens",
        "token strategy",
        "blueprint",
        "figma library",
        "shared components",
      ],
      weight: 1.2,
    },
    {
      id: "engineering_partnership",
      label: "Cross-functional engineering partnership",
      signals: [
        "partner with engineering",
        "engineering collaboration",
        "design engineering",
        "design ops",
        "design technologist",
        "react components",
        "implementation",
      ],
      weight: 1.0,
    },
    {
      id: "accessibility",
      label: "Accessibility",
      signals: [
        "accessibility",
        "wcag",
        "a11y",
        "inclusive design",
        "accessible components",
      ],
      weight: 1.0,
    },
    {
      id: "documentation",
      label: "Documentation",
      signals: [
        "documentation",
        "design specs",
        "contribution model",
        "design guidelines",
        "storybook",
        "design system documentation",
      ],
      weight: 1.0,
    },
    {
      id: "governance",
      label: "Governance",
      signals: [
        "governance",
        "design standards",
        "quality bar",
        "review process",
        "system health",
        "contribution guidelines",
      ],
      weight: 1.1,
    },
    {
      id: "adoption",
      label: "Adoption",
      signals: [
        "adoption",
        "enablement",
        "rollout",
        "migration",
        "system adoption",
        "design system adoption",
      ],
      weight: 1.1,
    },
    {
      id: "product_enablement",
      label: "Product team enablement",
      signals: [
        "enable product teams",
        "cross-product",
        "multiple product surfaces",
        "product partnership",
        "design partners",
      ],
      weight: 0.9,
    },
    {
      id: "metrics_impact",
      label: "Metrics and business impact",
      signals: [
        "metrics",
        "impact",
        "velocity",
        "efficiency",
        "business outcomes",
        "okr",
        "measure success",
      ],
      weight: 0.8,
    },
    {
      id: "large_scale_platform",
      label: "Large-scale platform/product design",
      signals: [
        "at scale",
        "large scale",
        "millions of users",
        "enterprise",
        "platform",
        "ecosystem",
        "multiple teams",
      ],
      weight: 0.9,
    },
  ],

  designSystemsSignals: {
    strong: [
      "design system",
      "design systems",
      "component library",
      "ui system",
      "product system",
      "platform design",
      "design infrastructure",
      "design tooling",
      "design platform",
    ],
    medium: [
      "systems thinking",
      "scalable ux",
      "cross-product patterns",
      "ui consistency",
      "pattern library",
      "shared patterns",
      "design language",
    ],
  },

  senioritySignals: {
    strong: [
      "staff",
      "principal",
      "lead",
      "ic6",
      "senior staff",
      "distinguished",
    ],
    medium: ["senior product designer", "senior designer", "sr. product designer"],
    penalize: [
      "manager",
      "director",
      "head of design",
      "vp of design",
      "vice president",
      "junior",
      "entry level",
      "associate designer",
      "intern",
      "mid-level",
      "mid level",
    ],
  },

  negativeSignals: [
    { pattern: "people manager", penalty: 0.9, label: "manager-only responsibilities" },
    { pattern: "manage a team", penalty: 0.85, label: "team management focus" },
    { pattern: "hiring and coaching", penalty: 0.7, label: "people management" },
    { pattern: "brand design", penalty: 0.6, label: "brand/marketing focus" },
    { pattern: "marketing design", penalty: 0.65, label: "marketing focus" },
    { pattern: "visual design lead", penalty: 0.5, label: "visual brand focus" },
    { pattern: "user research", penalty: 0.55, label: "research-only lean" },
    { pattern: "ux researcher", penalty: 0.8, label: "research role" },
    { pattern: "content designer", penalty: 0.85, label: "content design role" },
    { pattern: "content design", penalty: 0.75, label: "content design role" },
    { pattern: "motion design", penalty: 0.8, label: "motion design role" },
    { pattern: "3d design", penalty: 0.85, label: "3D design role" },
    { pattern: "industrial design", penalty: 0.9, label: "industrial design role" },
  ],

  roleFocusMapping: {
    design_systems: ["design system", "component library", "design infrastructure"],
    product_design: ["product designer", "product design"],
    platform_design: ["platform design", "platform designer"],
    ai_product_design: ["ai product", "ai designer", "ml product"],
    ux_infrastructure: ["ux infrastructure", "design platform", "design ops"],
    design_tooling: ["design tooling", "design tools", "figma plugin"],
    accessibility: ["accessibility", "a11y", "inclusive design"],
  },
} as const;

export type CandidateProfile = typeof CANDIDATE_PROFILE;
