import type { CompanyConfig } from "@/types";

/**
 * Configurable seed list of major technology companies and career page / ATS details.
 * Edit this file to add companies or update board tokens.
 *
 * ATS board tokens are typically found in career page URLs:
 * - Greenhouse: boards.greenhouse.io/{token}
 * - Lever: jobs.lever.co/{token}
 * - Ashby: jobs.ashbyhq.com/{token}
 */
export const TECH_COMPANIES: CompanyConfig[] = [
  { name: "Meta", domain: "meta.com", ticker: "META", isPublic: true, careersUrl: "https://www.metacareers.com/", ats: { type: "greenhouse", boardToken: "meta" } },
  { name: "Google", domain: "google.com", ticker: "GOOGL", isPublic: true, careersUrl: "https://careers.google.com/" },
  { name: "Waymo", domain: "waymo.com", ticker: "GOOGL", isPublic: true, careersUrl: "https://waymo.com/careers/", ats: { type: "greenhouse", boardToken: "waymo" } },
  { name: "DeepMind", domain: "deepmind.com", ticker: "GOOGL", isPublic: true, careersUrl: "https://deepmind.google/careers/", ats: { type: "greenhouse", boardToken: "deepmind" } },
  { name: "Wing", domain: "wing.com", ticker: "GOOGL", isPublic: true, careersUrl: "https://wing.com/careers/", ats: { type: "greenhouse", boardToken: "wing" } },
  { name: "Apple", domain: "apple.com", ticker: "AAPL", isPublic: true, careersUrl: "https://jobs.apple.com/" },
  { name: "Microsoft", domain: "microsoft.com", ticker: "MSFT", isPublic: true, careersUrl: "https://careers.microsoft.com/" },
  { name: "Amazon", domain: "amazon.com", ticker: "AMZN", isPublic: true, careersUrl: "https://www.amazon.jobs/" },
  { name: "Netflix", domain: "netflix.com", ticker: "NFLX", isPublic: true, careersUrl: "https://jobs.netflix.com/", ats: { type: "lever", boardToken: "netflix" } },
  { name: "Stripe", domain: "stripe.com", ticker: null, isPublic: false, careersUrl: "https://stripe.com/jobs", ats: { type: "greenhouse", boardToken: "stripe" } },
  { name: "Figma", domain: "figma.com", ticker: null, isPublic: false, careersUrl: "https://www.figma.com/careers/", ats: { type: "greenhouse", boardToken: "figma" } },
  { name: "Notion", domain: "notion.so", ticker: null, isPublic: false, careersUrl: "https://www.notion.so/careers", ats: { type: "greenhouse", boardToken: "notion" } },
  { name: "Airbnb", domain: "airbnb.com", ticker: "ABNB", isPublic: true, careersUrl: "https://careers.airbnb.com/", ats: { type: "greenhouse", boardToken: "airbnb" } },
  { name: "Uber", domain: "uber.com", ticker: "UBER", isPublic: true, careersUrl: "https://www.uber.com/us/en/careers/", ats: { type: "greenhouse", boardToken: "uber" } },
  { name: "Lyft", domain: "lyft.com", ticker: "LYFT", isPublic: true, careersUrl: "https://www.lyft.com/careers", ats: { type: "greenhouse", boardToken: "lyft" } },
  { name: "Spotify", domain: "spotify.com", ticker: "SPOT", isPublic: true, careersUrl: "https://www.lifeatspotify.com/", ats: { type: "lever", boardToken: "spotify" } },
  { name: "Shopify", domain: "shopify.com", ticker: "SHOP", isPublic: true, careersUrl: "https://www.shopify.com/careers", ats: { type: "greenhouse", boardToken: "shopify" } },
  { name: "Square", domain: "squareup.com", ticker: "SQ", isPublic: true, careersUrl: "https://careers.squareup.com/", ats: { type: "greenhouse", boardToken: "square" } },
  { name: "Block", domain: "block.xyz", ticker: "SQ", isPublic: true, careersUrl: "https://block.xyz/careers", ats: { type: "greenhouse", boardToken: "block" } },
  { name: "Coinbase", domain: "coinbase.com", ticker: "COIN", isPublic: true, careersUrl: "https://www.coinbase.com/careers", ats: { type: "greenhouse", boardToken: "coinbase" } },
  { name: "Robinhood", domain: "robinhood.com", ticker: "HOOD", isPublic: true, careersUrl: "https://careers.robinhood.com/", ats: { type: "greenhouse", boardToken: "robinhood" } },
  { name: "Plaid", domain: "plaid.com", ticker: null, isPublic: false, careersUrl: "https://plaid.com/careers/", ats: { type: "lever", boardToken: "plaid" } },
  { name: "Brex", domain: "brex.com", ticker: null, isPublic: false, careersUrl: "https://www.brex.com/careers", ats: { type: "greenhouse", boardToken: "brex" } },
  { name: "Ramp", domain: "ramp.com", ticker: null, isPublic: false, careersUrl: "https://ramp.com/careers", ats: { type: "ashby", boardToken: "ramp" } },
  { name: "Linear", domain: "linear.app", ticker: null, isPublic: false, careersUrl: "https://linear.app/careers", ats: { type: "ashby", boardToken: "linear" } },
  { name: "Vercel", domain: "vercel.com", ticker: null, isPublic: false, careersUrl: "https://vercel.com/careers", ats: { type: "greenhouse", boardToken: "vercel" } },
  { name: "Datadog", domain: "datadoghq.com", ticker: "DDOG", isPublic: true, careersUrl: "https://careers.datadoghq.com/", ats: { type: "greenhouse", boardToken: "datadog" } },
  { name: "Snowflake", domain: "snowflake.com", ticker: "SNOW", isPublic: true, careersUrl: "https://careers.snowflake.com/", ats: { type: "greenhouse", boardToken: "snowflake" } },
  { name: "Databricks", domain: "databricks.com", ticker: null, isPublic: false, careersUrl: "https://www.databricks.com/company/careers", ats: { type: "greenhouse", boardToken: "databricks" } },
  { name: "Cloudflare", domain: "cloudflare.com", ticker: "NET", isPublic: true, careersUrl: "https://www.cloudflare.com/careers/", ats: { type: "greenhouse", boardToken: "cloudflare" } },
  { name: "Twilio", domain: "twilio.com", ticker: "TWLO", isPublic: true, careersUrl: "https://www.twilio.com/company/jobs", ats: { type: "greenhouse", boardToken: "twilio" } },
  { name: "Atlassian", domain: "atlassian.com", ticker: "TEAM", isPublic: true, careersUrl: "https://www.atlassian.com/company/careers", ats: { type: "greenhouse", boardToken: "atlassian" } },
  { name: "Slack", domain: "slack.com", ticker: "CRM", isPublic: true, careersUrl: "https://slack.com/careers", ats: { type: "greenhouse", boardToken: "slack" } },
  { name: "Salesforce", domain: "salesforce.com", ticker: "CRM", isPublic: true, careersUrl: "https://careers.salesforce.com/" },
  { name: "Adobe", domain: "adobe.com", ticker: "ADBE", isPublic: true, careersUrl: "https://careers.adobe.com/", ats: { type: "workday", boardToken: "adobe" } },
  { name: "Autodesk", domain: "autodesk.com", ticker: "ADSK", isPublic: true, careersUrl: "https://www.autodesk.com/careers", ats: { type: "workday", boardToken: "autodesk" } },
  { name: "Canva", domain: "canva.com", ticker: null, isPublic: false, careersUrl: "https://www.canva.com/careers/", ats: { type: "greenhouse", boardToken: "canva" } },
  { name: "Discord", domain: "discord.com", ticker: null, isPublic: false, careersUrl: "https://discord.com/careers", ats: { type: "greenhouse", boardToken: "discord" } },
  { name: "Dropbox", domain: "dropbox.com", ticker: "DBX", isPublic: true, careersUrl: "https://www.dropbox.com/jobs", ats: { type: "greenhouse", boardToken: "dropbox" } },
  { name: "GitHub", domain: "github.com", ticker: "MSFT", isPublic: true, careersUrl: "https://github.com/careers" },
  { name: "GitLab", domain: "gitlab.com", ticker: "GTLB", isPublic: true, careersUrl: "https://about.gitlab.com/jobs/", ats: { type: "greenhouse", boardToken: "gitlab" } },
  { name: "HubSpot", domain: "hubspot.com", ticker: "HUBS", isPublic: true, careersUrl: "https://www.hubspot.com/careers", ats: { type: "greenhouse", boardToken: "hubspot" } },
  { name: "Intercom", domain: "intercom.com", ticker: null, isPublic: false, careersUrl: "https://www.intercom.com/careers", ats: { type: "greenhouse", boardToken: "intercom" } },
  { name: "LinkedIn", domain: "linkedin.com", ticker: "MSFT", isPublic: true, careersUrl: "https://careers.linkedin.com/", ats: { type: "greenhouse", boardToken: "linkedin" } },
  { name: "MongoDB", domain: "mongodb.com", ticker: "MDB", isPublic: true, careersUrl: "https://www.mongodb.com/careers", ats: { type: "greenhouse", boardToken: "mongodb" } },
  { name: "Okta", domain: "okta.com", ticker: "OKTA", isPublic: true, careersUrl: "https://www.okta.com/company/careers/", ats: { type: "greenhouse", boardToken: "okta" } },
  { name: "Pinterest", domain: "pinterest.com", ticker: "PINS", isPublic: true, careersUrl: "https://www.pinterestcareers.com/", ats: { type: "greenhouse", boardToken: "pinterest" } },
  { name: "Reddit", domain: "reddit.com", ticker: "RDDT", isPublic: true, careersUrl: "https://www.redditinc.com/careers", ats: { type: "greenhouse", boardToken: "reddit" } },
  { name: "Snap", domain: "snap.com", ticker: "SNAP", isPublic: true, careersUrl: "https://careers.snap.com/", ats: { type: "greenhouse", boardToken: "snap" } },
  { name: "Squarespace", domain: "squarespace.com", ticker: null, isPublic: false, careersUrl: "https://www.squarespace.com/careers", ats: { type: "greenhouse", boardToken: "squarespace" } },
  { name: "Twitch", domain: "twitch.tv", ticker: "AMZN", isPublic: true, careersUrl: "https://www.twitch.tv/jobs/", ats: { type: "greenhouse", boardToken: "twitch" } },
  { name: "Twitter", domain: "x.com", ticker: null, isPublic: false, careersUrl: "https://careers.x.com/" },
  { name: "Wayfair", domain: "wayfair.com", ticker: "W", isPublic: true, careersUrl: "https://www.aboutwayfair.com/careers", ats: { type: "greenhouse", boardToken: "wayfair" } },
  { name: "Zoom", domain: "zoom.us", ticker: "ZM", isPublic: true, careersUrl: "https://careers.zoom.us/", ats: { type: "greenhouse", boardToken: "zoom" } },
  { name: "Asana", domain: "asana.com", ticker: "ASAN", isPublic: true, careersUrl: "https://asana.com/jobs", ats: { type: "greenhouse", boardToken: "asana" } },
  { name: "Airtable", domain: "airtable.com", ticker: null, isPublic: false, careersUrl: "https://airtable.com/careers", ats: { type: "greenhouse", boardToken: "airtable" } },
  { name: "Amplitude", domain: "amplitude.com", ticker: "AMPL", isPublic: true, careersUrl: "https://amplitude.com/careers", ats: { type: "greenhouse", boardToken: "amplitude" } },
  { name: "Anthropic", domain: "anthropic.com", ticker: null, isPublic: false, careersUrl: "https://www.anthropic.com/careers", ats: { type: "greenhouse", boardToken: "anthropic" } },
  { name: "OpenAI", domain: "openai.com", ticker: null, isPublic: false, careersUrl: "https://openai.com/careers", ats: { type: "ashby", boardToken: "openai" } },
  { name: "Cruise", domain: "getcruise.com", ticker: "GM", isPublic: true, careersUrl: "https://getcruise.com/careers", ats: { type: "greenhouse", boardToken: "cruise" } },
  { name: "DoorDash", domain: "doordash.com", ticker: "DASH", isPublic: true, careersUrl: "https://careers.doordash.com/", ats: { type: "greenhouse", boardToken: "doordash" } },
  { name: "Instacart", domain: "instacart.com", ticker: "CART", isPublic: true, careersUrl: "https://instacart.careers/", ats: { type: "greenhouse", boardToken: "instacart" } },
  { name: "Duolingo", domain: "duolingo.com", ticker: "DUOL", isPublic: true, careersUrl: "https://careers.duolingo.com/", ats: { type: "greenhouse", boardToken: "duolingo" } },
  { name: "Epic Games", domain: "epicgames.com", ticker: null, isPublic: false, careersUrl: "https://www.epicgames.com/site/en-US/careers", ats: { type: "greenhouse", boardToken: "epicgames" } },
  { name: "HashiCorp", domain: "hashicorp.com", ticker: "HCP", isPublic: true, careersUrl: "https://www.hashicorp.com/careers", ats: { type: "greenhouse", boardToken: "hashicorp" } },
  { name: "Klaviyo", domain: "klaviyo.com", ticker: "KVYO", isPublic: true, careersUrl: "https://www.klaviyo.com/careers", ats: { type: "greenhouse", boardToken: "klaviyo" } },
  { name: "Loom", domain: "loom.com", ticker: "CRM", isPublic: true, careersUrl: "https://www.loom.com/careers", ats: { type: "greenhouse", boardToken: "loom" } },
  { name: "Miro", domain: "miro.com", ticker: null, isPublic: false, careersUrl: "https://miro.com/careers/", ats: { type: "greenhouse", boardToken: "miro" } },
  { name: "monday.com", domain: "monday.com", ticker: "MNDY", isPublic: true, careersUrl: "https://monday.com/careers", ats: { type: "greenhouse", boardToken: "mondaydotcom" } },
  { name: "Nvidia", domain: "nvidia.com", ticker: "NVDA", isPublic: true, careersUrl: "https://www.nvidia.com/en-us/about-nvidia/careers/" },
  { name: "Palantir", domain: "palantir.com", ticker: "PLTR", isPublic: true, careersUrl: "https://www.palantir.com/careers/", ats: { type: "lever", boardToken: "palantir" } },
  { name: "Rippling", domain: "rippling.com", ticker: null, isPublic: false, careersUrl: "https://www.rippling.com/careers", ats: { type: "ashby", boardToken: "rippling" } },
  { name: "Robinhood", domain: "robinhood.com", ticker: "HOOD", isPublic: true, careersUrl: "https://careers.robinhood.com/", ats: { type: "greenhouse", boardToken: "robinhood" } },
  { name: "ServiceNow", domain: "servicenow.com", ticker: "NOW", isPublic: true, careersUrl: "https://careers.servicenow.com/" },
  { name: "Splunk", domain: "splunk.com", ticker: "CSCO", isPublic: true, careersUrl: "https://www.splunk.com/en_us/careers.html", ats: { type: "greenhouse", boardToken: "splunk" } },
  { name: "Square Enix", domain: "square-enix.com", ticker: null, isPublic: false, careersUrl: "https://www.square-enix.com/en_US/careers.html" },
  { name: "Tesla", domain: "tesla.com", ticker: "TSLA", isPublic: true, careersUrl: "https://www.tesla.com/careers" },
  { name: "TikTok", domain: "tiktok.com", ticker: null, isPublic: false, careersUrl: "https://careers.tiktok.com/" },
  { name: "Toast", domain: "toasttab.com", ticker: "TOST", isPublic: true, careersUrl: "https://careers.toasttab.com/", ats: { type: "greenhouse", boardToken: "toast" } },
  { name: "Webflow", domain: "webflow.com", ticker: null, isPublic: false, careersUrl: "https://webflow.com/careers", ats: { type: "greenhouse", boardToken: "webflow" } },
  { name: "Wise", domain: "wise.com", ticker: "WISE", isPublic: true, careersUrl: "https://www.wise.jobs/", ats: { type: "greenhouse", boardToken: "transferwise" } },
  { name: "Zapier", domain: "zapier.com", ticker: null, isPublic: false, careersUrl: "https://zapier.com/jobs", ats: { type: "greenhouse", boardToken: "zapier" } },
  { name: "Zendesk", domain: "zendesk.com", ticker: "ZEN", isPublic: true, careersUrl: "https://www.zendesk.com/company/careers/", ats: { type: "greenhouse", boardToken: "zendesk" } },
  { name: "Elastic", domain: "elastic.co", ticker: "ESTC", isPublic: true, careersUrl: "https://www.elastic.co/careers", ats: { type: "greenhouse", boardToken: "elastic" } },
  { name: "Confluent", domain: "confluent.io", ticker: "CFLT", isPublic: true, careersUrl: "https://careers.confluent.io/", ats: { type: "greenhouse", boardToken: "confluent" } },
  { name: "CrowdStrike", domain: "crowdstrike.com", ticker: "CRWD", isPublic: true, careersUrl: "https://www.crowdstrike.com/careers/", ats: { type: "greenhouse", boardToken: "crowdstrike" } },
  { name: "Flexport", domain: "flexport.com", ticker: null, isPublic: false, careersUrl: "https://www.flexport.com/careers/", ats: { type: "greenhouse", boardToken: "flexport" } },
  { name: "Gusto", domain: "gusto.com", ticker: null, isPublic: false, careersUrl: "https://gusto.com/careers", ats: { type: "greenhouse", boardToken: "gusto" } },
  { name: "Hinge", domain: "hinge.co", ticker: "MTCH", isPublic: true, careersUrl: "https://hinge.co/careers", ats: { type: "greenhouse", boardToken: "hinge" } },
  { name: "Instabase", domain: "instabase.com", ticker: null, isPublic: false, careersUrl: "https://instabase.com/careers", ats: { type: "greenhouse", boardToken: "instabase" } },
  { name: "Lacework", domain: "lacework.com", ticker: null, isPublic: false, careersUrl: "https://www.lacework.com/careers", ats: { type: "greenhouse", boardToken: "lacework" } },
  { name: "Mercury", domain: "mercury.com", ticker: null, isPublic: false, careersUrl: "https://mercury.com/jobs", ats: { type: "ashby", boardToken: "mercury" } },
  { name: "Nuro", domain: "nuro.ai", ticker: null, isPublic: false, careersUrl: "https://www.nuro.ai/careers", ats: { type: "greenhouse", boardToken: "nuro" } },
  { name: "PagerDuty", domain: "pagerduty.com", ticker: "PD", isPublic: true, careersUrl: "https://careers.pagerduty.com/", ats: { type: "greenhouse", boardToken: "pagerduty" } },
  { name: "Samsara", domain: "samsara.com", ticker: "IOT", isPublic: true, careersUrl: "https://www.samsara.com/company/careers", ats: { type: "greenhouse", boardToken: "samsara" } },
  { name: "Snyk", domain: "snyk.io", ticker: null, isPublic: false, careersUrl: "https://snyk.io/careers/", ats: { type: "greenhouse", boardToken: "snyk" } },
  { name: "SoFi", domain: "sofi.com", ticker: "SOFI", isPublic: true, careersUrl: "https://www.sofi.com/careers/", ats: { type: "greenhouse", boardToken: "sofi" } },
  { name: "Tailscale", domain: "tailscale.com", ticker: null, isPublic: false, careersUrl: "https://tailscale.com/careers", ats: { type: "greenhouse", boardToken: "tailscale" } },
  { name: "Upwork", domain: "upwork.com", ticker: "UPWK", isPublic: true, careersUrl: "https://www.upwork.com/careers", ats: { type: "greenhouse", boardToken: "upwork" } },
  { name: "Watershed", domain: "watershed.com", ticker: null, isPublic: false, careersUrl: "https://watershed.com/careers", ats: { type: "ashby", boardToken: "watershed" } },
  { name: "Weights & Biases", domain: "wandb.ai", ticker: null, isPublic: false, careersUrl: "https://wandb.ai/careers", ats: { type: "greenhouse", boardToken: "wandb" } },
];

/** Design-related department keywords used to filter ATS postings */
export const DESIGN_DEPARTMENT_KEYWORDS = [
  "design",
  "product design",
  "ux",
  "user experience",
  "design systems",
  "creative",
];
